### ISSUE TITLE
Don't use BigtableDataClient directly

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#2067]
All of these references need to be removed.

 -  Dataflow
    - [x] `./bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableIO.java`.  Fixed in #2070

 - One offs
   - [x] `./bigtable-test/bigtable-emulator-maven-plugin/src/it/simple-it/src/test/java/SimpleIT.java`.  This was fixed in #2078.
   - [ ] `./bigtable-client-core-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/PutMicroBenchmark.java`.  This class should be removed.

 - Client Core
   - [ ] `./bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/async/TestBulkMutation.java`
   - [ ] `./bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/async/TestBulkMutationAwaitCompletion.java`
   - [x] `./bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/async/TestAsyncExecutor.java`. This was removed
   - [x] `./bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/async/TestBulkRead.java`.  Fixed in #2064
   - [x] `./bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/RetryingMutateRowsOperation.java` NOTE: This is only a reference via a comment, which is appropriate to keep.
   - [x] `./bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/BulkRead.java
   - [x] `./bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/AsyncExecutor.java`.  This class was removed
   - [ ] `./bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/BulkMutation.java` 
   - [x] `./bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/MutateRowsRequestManager.java` NOTE: This is only a reference via a comment, which is appropriate to keep, since `BigtableDataClient` uses this class.
 
 - HBase 1
   - [x] `./bigtable-client-core-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/TestBigtableTable.java`.
   - [x] `./bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableRegionLocator.java`.
   - [x] `./bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/AbstractBigtableTable.java`. 
   - [x] `./bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/AbstractBigtableRegionLocator.java`.  
 
 - HBase 2
   - [x] `./bigtable-hbase-2.x-parent/bigtable-hbase-2.x/src/main/java/com/google/cloud/bigtable/hbase2_x/BigtableAsyncTableRegionLocator.java`. 
   - [x] `./bigtable-hbase-2.x-parent/bigtable-hbase-2.x/src/main/java/com/google/cloud/bigtable/hbase2_x/BigtableDataClient.java`

**Comment by sduskis** [comment]
There are two major issues left:

1. *Bulk mutations* - We need a way to cheaply convert `MutateRowsRequet.Entry` protos to `model.Mutation`.  That needs a change in google-cloud-java
2. *ReadModifyWrite* - We need a way to convert the proto `Row` response to `model.Row`. That was implemented here: https://github.com/googleapis/google-cloud-java/pull/4458.  Once there's a new `google-cloud-bigtable` release, we can convert `ReadModifyWrite` to the wrapper.

**Comment by sduskis** [comment]
`ReadModifyWrite` is done.  `BulkMutations` is fine as is, and we use `IBulkMutation` for HBase, which meets our core objective.
